### ISSUE TITLE
Custom Allowlist for TLDs

### ISSUE THREAD

**Issue by simon-kolkmann** [andersju/webbkoll-backend#3]
We are currently selfhosting Webbkoll to test some internal web applications.
These apps use URLs which end with `.loc`. [This line](https://github.com/andersju/webbkoll-backend/blob/b0a819e884af1b2f6739ab06448219d201ec9dd4/index.js#L38) makes testing them impossible, because `.loc` is not recognized as a valid tld.

Is there a way to allow custom top level domains? And if not, would you be interested in a PR implementing this feature?

**Comment by andersju** [comment]
It's not supported in the backend, but it definitely should be. PR would be welcome, sure! :)

A simple change would be modifying that `if` so that no checking is done if `WEBBKOLL_ENV` is `dev`. This would make it consistent with the main Webbkoll app, where no validation is done if `validate_urls` is `false` (`config/dev.exs` has ` validate_urls: false`).

Maybe also make `validate_urls` a query parameter in `index.js`? So if `WEBBKOLL_ENV` is `dev`, or `request.query.validate_urls` is `false`, don't validate.

**Comment by simon-kolkmann** [comment]
> Maybe also make `validate_urls` a query parameter in `index.js`? So if `WEBBKOLL_ENV` is dev, or `request.query.validate_urls` is `false`, don't validate.

If the main app would always send `validate_urls=false` as query parameter when running in the `dev` environment, would it still be necessary to check `WEBBKOLL_ENV`?

Regarding the PR: I had hoped that this would be a backend-only change, as I have absolutely no experience with Elixir. :) I wanted to suggest adding a new environment variable (something like `CUSTOM_TLD_ALLOWLIST`) with an array of custom tlds which we could check.

However, I totally understand that you want to combine this with the existing `validate_urls` setting of the main app. I just can't do the PR then, sorry.

**Comment by andersju** [comment]
Ah, no need to change any Elixir code, I can do that if necessary.

I don't have strong opinions here; for your use case, are you fine with turning off validation completely? If so, then it's just a matter of setting the environment variable `WEBBKOLL_ENV=dev` and adding `if (WEBBKOLL_ENV !== 'dev') { ... }` around the code you mentioned. Currently, "dev" mode does nothing except turning off validation.

If you do need validation-but-also-custom-TLDs (through a new environment variable), I'm fine with such a feature too! Just note that there's domain validation code in two places: [the line you mentioned](https://github.com/andersju/webbkoll-backend/blob/b0a819e884af1b2f6739ab06448219d201ec9dd4/index.js#L38), which happens before Chromium is launched, and [here](https://github.com/andersju/webbkoll-backend/blob/b0a819e884af1b2f6739ab06448219d201ec9dd4/index.js#L68-L85), which checks each actual request made by Chromium and decides whether to block it or not.

**Comment by simon-kolkmann** [comment]
> I don't have strong opinions here; for your use case, are you fine with turning off validation completely?

Yes, turning off validation completely would be enough for my use case. 

I still like the idea that the main app communicates this setting with a query parameter. Couldn't we remove `WEBBKOLL_ENV` completely then?

**Comment by andersju** [comment]
Yeah, no need for `WEBBKOLL_ENV` then. If the query parameter isn't specified, the default action should be to validate URLs. I can make the change in the Elixir Webbkoll app to use the query parameter if `validate_urls: false` under `config :webbkoll` in `config/{dev,prod}.exs`.

**Comment by andersju** [comment]
I made small change on the Elixir side (andersju/webbkoll@7325c1c), so the setting `validate_urls` in `config/{dev,prod}.exs` will now set the backend query parameter accordingly.

**Comment by simon-kolkmann** [comment]
Great, thanks!
